
name: .NET Playwright CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node (for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Restore NuGet packages
        run: dotnet restore tests/Kmslh.Tests.csproj

      - name: Run tests
        run: dotnet test tests/Kmslh.Tests.csproj --logger trx
