name: .NET Playwright CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node (for Playwright)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore NuGet packages
        run: dotnet restore tests/Kmslh.Tests.csproj

      - name: Build test project (required for playwright CLI)
        run: dotnet build tests/Kmslh.Tests.csproj

      - name: Install Playwright CLI tool globally
        run: dotnet tool install --global Microsoft.Playwright.CLI

      - name: Add dotnet global tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Playwright browsers
        run: playwright install

      - name: Run tests
        run: dotnet test tests/Kmslh.Tests.csproj --logger trx